services:
  redis_gaming:
    image: redis:7-alpine
    container_name: redis_gaming
    ports:
      - "${REDIS_HOST_PORT:-6380}:6379"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 10
  postgres_gaming:
    image: postgres:17.11-alpine
    container_name: postgres_gaming
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_HOST_PORT:-5436}:5432"
    volumes:
      - postgres_gaming:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s


volumes:
  postgres_gaming:
