spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_HOST_PORT:5436}/${POSTGRES_DB:gaming_gear_db}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_HOST_PORT:6380}

  cache:
    type: redis
    cache-names:
      - categories
      - brands
      - product-list
      - product-detail

logging:
  level:
    org.hibernate.SQL: debug
