spring:
  application:
    name: gaming-gear
  profiles:
    default: dev
  config:
    import: optional:file:.env[.properties]
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration

security:
  jwt:
    secret: ${JWT_SECRET_BASE64}
    expiration: 900000
    refresh-expiration: 2592000000