create table orders(
    id bigint generated by default as identity primary key ,
    user_id bigint not null ,
    recipient_name varchar(100) not null ,
    recipient_phone varchar(20) not null ,
    shipping_address varchar(255) not null ,
    note varchar(255) ,
    status varchar(30) not null default 'PENDING',
    payment_method varchar(30) not null default 'COD',
    total_amount numeric(12,2) not null check ( total_amount >= 0 ),
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp,

    constraint chk_orders_status
          check ( status in ('PENDING', 'CONFIRMED' , 'SHIPPING' , 'DELIVERED', 'CANCELLED')),

    constraint chk_orders_payment_method
          check ( payment_method in ('COD')),

    constraint fk_orders_user
          foreign key (user_id) references users (id) on delete restrict
);

create table order_items(
    id bigint generated by default as identity primary key ,
    order_id bigint not null ,
    product_variant_id bigint not null ,
    product_name varchar(150) not null ,
    variant_name varchar(150) not null ,
    sku varchar(100) not null ,
    unit_price numeric(12,2) not null check ( unit_price >=0 ),
    quantity integer not null check ( quantity >= 0 ),
    line_total numeric(12,2) not null check ( line_total >= 0 ),
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp,

    constraint uk_order_items_order_variant
        unique (order_id,product_variant_id),

    constraint fk_order_items_order
        foreign key (order_id) references orders (id) on DELETE cascade ,

    constraint fk_order_items_product_variant
        foreign key (product_variant_id) references product_variants (id) on DELETE restrict

);

CREATE INDEX idx_orders_user_id
    ON orders (user_id);

CREATE INDEX idx_orders_status
    ON orders (status);

CREATE INDEX idx_order_items_order_id
    ON order_items (order_id);

CREATE INDEX idx_order_items_product_variant_id
    ON order_items (product_variant_id);