create table cms_banners(
    id bigint generated by default as identity primary key ,
    title varchar(150) not null ,
    image_object_key varchar(500) not null ,
    redirect_url varchar(500) ,
    position varchar(30) not null ,
    sort_order integer not null default 0,
    status varchar(30) not null default 'DRAFT',
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp,

    constraint chk_cms_banners_sort_order check ( sort_order >= 0 ),
    constraint chk_cms_banners_position check ( position in ('HOME_HERO','HOME_PROMOTION')),
    constraint chk_cms_banners_status check ( status in ('DRAFT','PUBLISHED','ARCHIVED') )
);

create table cms_pages(
    id bigint generated by default as identity primary key ,
    title varchar(150) not null ,
    slug varchar(200) not null ,
    content TEXT not null ,
    meta_title varchar(150),
    meta_description varchar(300),
    status varchar(30) not null default 'DRAFT',
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp,

    CONSTRAINT uk_cms_pages_slug UNIQUE (slug),

    CONSTRAINT chk_cms_pages_status
      CHECK (status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED'))
);

create table cms_articles(
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     title VARCHAR(150) NOT NULL,
     slug VARCHAR(200) NOT NULL,
     excerpt VARCHAR(500),
     content TEXT NOT NULL,
     cover_image_object_key VARCHAR(500),
     meta_title VARCHAR(160),
     meta_description VARCHAR(300),
     status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
     published_at TIMESTAMPTZ,
     created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
     updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

     CONSTRAINT uk_cms_articles_slug UNIQUE (slug),

     CONSTRAINT chk_cms_articles_status
         CHECK (status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED'))
);

CREATE INDEX idx_cms_banners_public
    ON cms_banners (position, status, sort_order, id);

CREATE INDEX idx_cms_articles_public
    ON cms_articles (status, published_at DESC, id DESC);
